### ISSUE TITLE
ngc "--project" "tsconfig.build.json" failing

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng-formly#376]
while `npm install` in the project, I see that this step `ngc "--project" "tsconfig.build.json"` is failing 

```
Error at /Users/zamamoha/Desktop/v2/ng2-formly/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /Users/zamamoha/Desktop/v2/ng2-formly/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at /Users/zamamoha/Desktop/v2/ng2-formly/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
```

**Comment by aitboudad** [comment]
can you try with `yarn install` ?

**Comment by mohammedzamakhan** [comment]
I was trying to publish to npm using npm publish

**Comment by aitboudad** [comment]
see #377
