### ISSUE TITLE
[v2] drop support of angular 2

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng-formly#461]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Comment by NomanYaqoob** [comment]
@aitboudad  any plan for Angular 4 updates ?

**Comment by aitboudad** [comment]
@NomanYaqoob Angular 4 is already supported, have you encountered any issue ?

**Comment by NomanYaqoob** [comment]
yup. please check out this, I haven't change any code in my module.. I just updated the following
"@angular/core": "^4.2.4",
"ng-formly": "^1.0.0-rc.10",

Error:
FormlyFieldInput.html:2 ERROR TypeError: Cannot read property 'templateOptions' of undefined
    at FormlyAttributes.ngOnChanges (http://localhost:3000/1.chunk.js:1574:68)
    at checkAndUpdateDirectiveInline (http://localhost:3000/vendor.bundle.js:11178:19)
    at checkAndUpdateNodeInline (http://localhost:3000/vendor.bundle.js:12677:17)
    at checkAndUpdateNode (http://localhost:3000/vendor.bundle.js:12616:16)
    at debugCheckAndUpdateNode (http://localhost:3000/vendor.bundle.js:13477:59)
    at debugCheckDirectivesFn (http://localhost:3000/vendor.bundle.js:13418:13)
    at Object.View_FormlyFieldInput_0._co [as updateDirectives] (ng:///FormlyBootstrapModule/FormlyFieldInput.ngfactory.js:59:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/vendor.bundle.js:13403:21)
    at checkAndUpdateView (http://localhost:3000/vendor.bundle.js:12583:14)

**Comment by NomanYaqoob** [comment]
@aitboudad but now the issue is resolved, thanks for your feedback. I haven't notice about the package name has been changed.
